name: Unity

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
     name: Build
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1.1.0
        with:
          path: /Library
          key: Library-DungeonManager-WebGL
          restore-keys: |
            Library-DungeonManager-
            Library-
      - uses: webbertakken/unity-builder@v1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2019.4.4f1
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
