# This is a basic workflow to help you get started with Actions

name: Unity

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
     name: Build
     runs-on: ubuntu-latest
     steps:
      - uses: webbertakken/unity-builder@v1.1
        with:
  #      projectPath: path/to/your/project
          unityVersion: 2019.4.4f1
          targetPlatform: WebGL
